- name: General purpose copy
  ansible.builtin.copy:
    src: "{{  item.target_file }}"
    dest: "/{{  item.target_file }}"
    owner: "{{  item.owner }}"
    group: "{{  item.group }}"
    mode: "{{  item.mode }}"
  with_items:
    - "{{ general_purpose_copy_info }}"
  become: yes

